# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/ref.smk"

rule all:
    input:
        get_final_output