configfile: "config/config.yaml"


# declare main workflow as a module
module test_circle_map_workflow:
    snakefile:
        "../workflow/Snakefile"
    config:
        config


# use all rules from the main workflow
use rule * from test_circle_map_workflow


# add rules for testing setup


rule download_test_data:
    output:
        "results/data/unknown_circle_reads_{read}.fastq",
    log:
        "logs/data/unknown_circle_reads_{read}.fastq",
    shell:
        "wget -O {output} https://raw.githubusercontent.com/iprada/Circle-Map/master/tutorial/unknown_circle_reads_{wildcards.read}.fastq 2> {log}"
