$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake workflow configuration file

type: object

properties:
  samples:
    type: string
  units:
    type: string
  groups:
    type: string

  ref:
    type: object
    properties:
      n_chromosomes:
        type: integer
      species:
        type: string
      release:
        type: integer
      build:
        type: string
    required:
      - species
      - release
      - build
      - n_chromosomes

required:
  - samples
  - units
  - ref
