$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake workflow configuration file

type: object

properties:
  samples:
    type: string
  units:
    type: string
  groups:
    type: string

  ref:
    type: object
    properties:
      n_chromosomes:
        type: integer
      species:
        type: string
      release:
        type: integer
      build:
        type: string
    required:
      - species
      - release
      - build
      - n_chromosomes
  circle_filtering:
    type: object
    properties:
      min_circle_score:
        type: number
      min_split_reads:
        type: integer
      min_discordant_read_pairs:
        type: integer
      max_uncovered fraction:
        type: number
      min_mean_coverage:
        type: number
      min_circle_length:
        type: integer
      max_circle_length:
        type: integer
    required:
      - min_circle_score
      - min_split_reads
      - min_discordant_read_pairs
      - max_uncovered fraction
      - min_mean_coverage
      - min_circle_length
      - max_circle_length

required:
  - samples
  - units
  - ref
  - circle_filtering
